kafka:
  brokers: ["redpanda:9092"]
  schemaRegistry:
    enabled: true
    urls: ["http://redpanda:8081"]

redpanda:
  adminApi:
    enabled: true
    urls: ["http://redpanda:9644"]

server:
  listenAddress: 0.0.0.0:8080
  compression:
    enabled: true
    level: 4

console:
  topicDocumentationEnabled: true